export const CODE_SEND_ERRORS = 'CODE_SEND_ERROR';
export const VERIFY_CODE_SEND_ERRORS = 'VERIFY_CODE_SEND_ERROR';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const FETCH_ALL_DATAS = 'FETCH_ALL_DATAS';
export const GET_NOTICE = 'GET_NOTICE';